export const APP_CONFIG = {
  name: "FlowCMS",
  tagline: "Structured content for modern teams",
  description:
    "FlowCMS is an open-source headless CMS with a visual block editor and predictable REST APIs.",
  url: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
  apiUrl: process.env.NEXT_PUBLIC_API_URL ?? "https://getflowcms.com/api",
  docsUrl: "https://getflowcms.com/docs",
  githubUrl: "https://github.com/kjxcodez/FlowCMS",
  nav: [
    { label: "Features", href: "#features" },
    { label: "How it works", href: "#how-it-works" },
    { label: "API", href: "#api" },
    { label: "Pricing", href: "#pricing" },
  ],
  tickerItems: [
    "Open source friendly",
    "REST API",
    "Type-safe with Prisma",
    "Next.js ready",
    "Block-based editor",
    "Multi-environment",
    "Webhook support",
    "Role-based access",
    "Image optimization",
    "Draft previews",
    "SEO metadata fields",
    "JSON schema",
  ],
  pricing: [
    {
      plan: "Hobby",
      planKey: "HOBBY",
      price: "₹0",
      period: "Free forever",
      featured: false,
      cta: "Current Plan",
      features: [
        "3 content types",
        "5,000 API requests/mo",
        "3 AI generations/day",
        "1 environment (Prod)",
      ],
    },
    {
      plan: "Pro",
      planKey: "PRO_MONTHLY",
      price: "₹1,999",
      period: "per month",
      featured: true,
      cta: "Upgrade to Pro",
      features: [
        "Unlimited content types",
        "250,000 API requests/mo",
        "20 AI generations/day",
        "2 environments (Staging/Prod)",
        "Draft previews",
        "Webhooks",
      ],
    },
    {
      plan: "Agency",
      planKey: "AGENCY_MONTHLY",
      price: "₹6,499",
      period: "per month",
      featured: false,
      cta: "Upgrade to Agency",
      features: [
        "1,000,000 API requests/mo",
        "50 AI generations/day",
        "5 environments",
        "Custom roles",
        "White-label support",
        "Priority assistance",
      ],
    },
  ],
  footerLinks: ["Docs", "API Reference", "Changelog", "GitHub", "Privacy", "Terms"],
  copyright: "All rights reserved.",
} as const;
