export const APP_CONFIG = {
  name: "FlowCMS",
  tagline: "Structured content for modern teams",
  description:
    "FlowCMS is an open-source headless CMS with a visual block editor and predictable REST APIs.",
  url: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
  apiUrl: process.env.NEXT_PUBLIC_API_URL ?? "https://api.flowcms.dev",
  docsUrl: "https://docs.flowcms.dev",
  githubUrl: "https://github.com/kjxcodez/FlowCMS",
  nav: [
    { label: "Features", href: "#features" },
    { label: "How it works", href: "#how-it-works" },
    { label: "API", href: "#api" },
    { label: "Pricing", href: "#pricing" },
  ],
  tickerItems: [
    "Open source friendly",
    "REST API",
    "Type-safe with Prisma",
    "Next.js ready",
    "Block-based editor",
    "Multi-environment",
    "Webhook support",
    "Role-based access",
    "Image optimization",
    "Draft previews",
    "SEO metadata fields",
    "JSON schema",
  ],
  pricing: [
    {
      plan: "Hobby",
      price: "Free",
      period: "Always free",
      featured: false,
      cta: "Start free",
      features: [
        "3 content types",
        "5,000 API requests/mo",
        "1 environment",
        "Community support",
      ],
    },
    {
      plan: "Pro",
      price: "$19",
      period: "per month",
      featured: true,
      cta: "Get started",
      features: [
        "Unlimited content types",
        "500k API requests/mo",
        "3 environments",
        "Webhooks",
        "Priority support",
      ],
    },
    {
      plan: "Team",
      price: "$79",
      period: "per month",
      featured: false,
      cta: "Contact us",
      features: [
        "Everything in Pro",
        "Unlimited environments",
        "Custom roles",
        "SSO",
        "SLA support",
      ],
    },
  ],
  footerLinks: ["Docs", "API Reference", "Changelog", "GitHub", "Privacy", "Terms"],
  copyright: "All rights reserved.",
} as const;
